# If a course has one of these tags in the course name, it belongs to
# this category, but not necessarily ONLY this category
# These categories also overlap with attributes *

departments = {
    'ACC': 'Accountancy',
    'AAH': 'Art and Art History',
    'AST': 'Astronomy and Astrophysics',
    'ACS': 'Augustine and Culture Seminar',
    'BIO': 'Biology',
    'BL': 'Business Law',
    'CHE': 'Chemical Engineering',
    'CHM': 'Chemistry',
    'CHI': 'Chinese',
    'MSCM': 'Church Management',
    'CEE': 'Civil and Environmental Engineering',
    'CLA': 'Classical Studies',
    'CBN': 'Cognitive and Behavioral Neuroscience',
    'CGS': 'Cognitive Science',
    'COM': 'Communication',
    'CSC': 'Computer Science',
    'COU': 'Counseling',
    'CHR': 'Counseling and Human Relations',
    #'''Criminal Justice', Not sure if this exists?
    'CRM': 'Criminology',
    'CST': 'Cultural Studies',
    'ECO': 'Economics',
    'EDU': 'Education',
    'ECE': 'Electrical and Computer Engineering',
    'EGR': 'Engineering',
    'EGEN': 'Engineering Entrepreneurship',
    'ETH': 'Ethics',
    'FRE': 'French',
    'GWS': 'Gender and Woman Studies',
    'GEV': 'Geography and the Environment',
    'GIS': 'Gloval Interdisciplinary Studies',
    'GLY': 'Geology',
    'GRK': 'Greek',
    'HIS': 'History',
    'HON': 'Honors',
    'HRD': 'Human Resource Development',
    'HS': 'Human Services',
    'HUM': 'Humanities',
    'IS': 'Irish Studies',
    'ITA': 'Italian',
    'JPN': 'Japanese',
    'LAT': 'Latin',
    'LAS': 'Latin American Studies',
    'LAW': 'Law',
    'LDR': 'Leadership',
    'LA': 'Liberal Arts',
    'LST': 'Liberal Studies',
    'MGT': 'Management',
    'MIS': 'Management Information Systems',
    'MKT': 'Marketing',
    'MAC': 'Master in Accounting/Prof Cons', #WTF is Prof Cons?
    'MET': 'Meteorology',
    'MS': 'Military Science',
    'NS': 'Naval Science',
    'NUR': 'Nursing',
    'NTR': 'Nutrition',
    'PJ': 'Peace and Justice',
    'PHI': 'Philosophy',
    'PHY': 'Physics',
    'PSC': 'Political Science',
    'PSY': 'Psychology',
    'POR': 'Portugese',
    'ASPD': 'Professional Development for Arts and Sciences',
    'MPA': 'Public Administration',
    'PA': 'Public Administration Undergraduate',
    'RES': 'Real Estate',
    'CRS': 'Recovery Specialist',
    'RUS': 'Russian',
    'RLL': 'Romance Languagues and Literature',
    #'Russian Area Studies',
    'VSB': 'School of Business',
    'SL': 'Service Learning',
    #'Social Science',
    'SOC': 'Sociology',
    'SPA': 'Spanish',
    'SAR': 'Studio Art and Music',
    'VAB': 'Study Abroad',
    'LTX': 'Taxation',
    'THE': 'Theatre',
    'THL': 'Theology and Religious Studies',
    'VEXP': 'Villanova Experience',
    'ACC': 'Accountancy',
    'ARB': 'Arabic',
    'ENG': 'English',
    'ENT': 'Entrepreneurship Management',
    #'''Environmental Studies',
    'EMB': 'Executive MBA',
    'FIN': 'Finance',
    'MSA': 'Master of Science in Analytics',
    'MSF': 'Master of Science in Finance',
    'MBA': 'Master of Business Administration',
    'MAT': 'Mathematics',
    'ME': 'Mechanical Engineering',
    'MSE': 'Mendel Science Experiment',
    'SCI': ''   # This isn't right. Find out what SCI is
}
