courses = [{'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Algorithms & Data Struc I', 'location': None, 'enrollment': u'21 of 28', 'section_number': u'001', 'days': None, 'course_number': u'1051', 'end_time': None, 'attributes': [], 'instructor': [u'Mary Angela Papalaskari'], 'crn': u'32968', 'start_time': None, 'subject': u'CSC'},
           {'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Algorithms & Data Struc I', 'location': None, 'enrollment': u'FULL 28', 'section_number': u'002', 'days': None, 'course_number': u'1051', 'end_time': None, 'attributes': [], 'instructor': [u'Mary Angela Papalaskari'], 'crn': u'32969', 'start_time': None, 'subject': u'CSC'},
           {'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Algorithms & Data Struc I', 'location': None, 'enrollment': u'FULL 31', 'section_number': u'100', 'days': None, 'course_number': u'1051', 'end_time': None, 'attributes': [], 'instructor': [u'Sarah M. Lehman'], 'crn': u'32970', 'start_time': None, 'subject': u'CSC'},
           {'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Algorithms & Data Struc II', 'location': None, 'enrollment': u'27 of 28', 'section_number': u'001', 'days': None, 'course_number': u'1052', 'end_time': None, 'attributes': [], 'instructor': [u'Edward Kim'], 'crn': u'32971', 'start_time': None, 'subject': u'CSC'},
           {'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Algorithms & Data Struc II', 'location': None, 'enrollment': u'9 of 28', 'section_number': u'002', 'days': None, 'course_number': u'1052', 'end_time': None, 'attributes': [], 'instructor': [u'Foster M McGeary'], 'crn': u'32972', 'start_time': None, 'subject': u'CSC'},
           {'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Algorithms & Data Struc II', 'location': None, 'enrollment': u'12 of 25', 'section_number': u'100', 'days': None, 'course_number': u'1052', 'end_time': None, 'attributes': [], 'instructor': [u'Evariste Some'], 'crn': u'32973', 'start_time': None, 'subject': u'CSC'},
           {'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Analysis of Algorithms', 'location': None, 'enrollment': u'32 of 33', 'section_number': u'001', 'days': None, 'course_number': u'1700', 'end_time': None, 'attributes': [], 'instructor': [u'Anany Levitin'], 'crn': u'32978', 'start_time': None, 'subject': u'CSC'},
           {'comment': '', 'restrictions': [u'Must be enrolled in one of the following Levels: Undergraduate', u'May not be enrolled in one of the following Campuses: University Alliance'], 'course_name': u'Analysis of Algorithms', 'location': None, 'enrollment': u'FULL 33', 'section_number': u'002', 'days': None, 'course_number': u'1700', 'end_time': None, 'attributes': [], 'instructor': [u'Anany Levitin'], 'crn': u'32979', 'start_time': None, 'subject': u'CSC'}
]
